DELETE http://localhost:3001/api/notes/65b9e0bc4ea9da9e0e347690 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NWI5NGIwYjg4YjE0YzFiZTYxNTk4ZmYiLCJpYXQiOjE3MDY2Nzk4NjIsImV4cCI6MTcwNjY4MzQ2Mn0.ZSGSKP7rzIoWRgJtxyJsKZm-d96YjpNEn6y_qHiPV88
